### ISSUE TITLE
Start button does not work

### ISSUE THREAD

**Issue by SCuellar80** [AlexandrePTJ/kemai#106]
First time using Desktop Client for Kimai (Windows 10 Enterprise version).
After basic configuration of my Profile (Host, Username and Token) it seems the start button does not work.
Every time I push the start button, I get this error:

> [2023-09-16 19:38:33.413] [kemai] [debug] [POST] http://severiano.kimai.cloud/api/timesheets
> [2023-09-16 19:38:33.985] [kemai] [debug] [RECV] timesheets
> [2023-09-16 19:38:33.985] [kemai] [error] <=== JSON value is not an object

Kemai version 0.10.0 but tested several previous versions and they did not work either.

Do I need to configure something else to make it work? Or this is a real issue? I did not find anything related on Discussion section.

**Comment by AlexandrePTJ** [comment]
@SCuellar80 Did you try using https instead of http ?

**Comment by SCuellar80** [comment]
I configured the Host as your suggestion:

> https://user.kimai.cloud/

Restarted the app (otherwise it was still sending http) and the button is now working!

Thank you!
