### ISSUE TITLE
Add support for API Token

### ISSUE THREAD

**Issue by AlexandrePTJ** [AlexandrePTJ/kemai#116]
https://www.kimai.org/documentation/rest-api.html

**Comment by kevinpapst** [comment]
Came here to post that Feature request, but you were quicker 👍 

That would be nice and it could also force users to upgrade their Kimai to a recent version 😁

**Comment by AlexandrePTJ** [comment]
@kevinpapst After running some tests, it does really improve response delay ! Good work !
So I will make it more "mandatory" for the new UI refactoring.
