### ISSUE TITLE
invalid credentials

### ISSUE THREAD

**Issue by uniseller-io** [AlexandrePTJ/kemai#119]
When I test credentials in Kemai settings I'm getting an answer {"message": "invalid credentials"}. Same token tested in Postman with success. What could be the problem? Log "GET /api/version HTTP/1.0" 403 33 "-" "Kemai/0.10.0"

**Comment by virtulis** [comment]
I think the token authentication only works in the development version, have you tried that?

**Comment by AlexandrePTJ** [comment]
@uniseller-io Sorry for the late response.
@virtulis Yes it is true. So released version of Kemai still needs user/password.
I plan to release a version to support token asap.

**Comment by AlexandrePTJ** [comment]
I just release 0.11.0 which allows API token.
