### ISSUE TITLE
VCRUNTIME140_1.dll was not found

### ISSUE THREAD

**Issue by ken14505** [AlexandrePTJ/kemai#19]
Downloaded MSI and installed on Windows 10 system. Installation seemed successful. However, when I ran (using the shortcut/icon added to my desktop), I get this.

![image](https://user-images.githubusercontent.com/31363129/97087587-0e32cd00-15e0-11eb-8112-a0c2f7e8cf8f.png)

Any ideas?

I am running Windows 10 Pro, v1909, OS build 18363.1082.

**Comment by AlexandrePTJ** [comment]
This component is part of "VisualC++ redistribuable 2019". It is required for software build with Visual Studio 2019.
You can find it here: https://aka.ms/vs/16/release/vc_redist.x64.exe
