### ISSUE TITLE
MacOS 10.14 support

### ISSUE THREAD

**Issue by zsirmo** [AlexandrePTJ/kemai#2]
Dear Alexander!

MacOS 10.14 (Mojave) support is possible?

Regards Attila

![image](https://user-images.githubusercontent.com/5598852/81280155-64bf4580-9058-11ea-8037-d5ab64ce1f73.png)

**Comment by zsirmo** [comment]
I compiled with old xcode(10.3), and stuff is working! :)

**Comment by AlexandrePTJ** [comment]
Hi,
Yes I will look on how to chnage minimal version.

**Comment by AlexandrePTJ** [comment]
Version 0.1.1 should fix this.
