### ISSUE TITLE
Use new API credentials without restart

### ISSUE THREAD

**Issue by ZeiP** [AlexandrePTJ/kemai#21]
When I first launched the program, it naturally failed to read the clients etc. from the API because of missing credentials. I added the credentials to settings but for the program to actually work I needed to restart it. It'd be a good idea to either notify the user of the need to restart or re-load the lists automatically after changing the credentials.

**Comment by AlexandrePTJ** [comment]
Which version do you use ? AppImage from release or did you build from source ?
Currently once credentials are filled and saved, Kemai redirect to main view and customers drop-down control is filled.

So I cannot reproduce the bug you have, so I will need more details.

**Comment by ZeiP** [comment]
I'm using the AppImage version, so it indeed may be already fixed in the source.

**Comment by AlexandrePTJ** [comment]
Current source correspond to AppImage version. So this is the same.
Does your kimai is instance is served through http or https ?

**Comment by ZeiP** [comment]
Ah, ok. The instance is served through https. I can try reproducing the problem; I'm certain that it happened once, but of course it can be some kind of one-of-a-kind bug.

**Comment by AlexandrePTJ** [comment]
Great, is it self-signed certificate ?

**Comment by ZeiP** [comment]
No, it's a Let's encrypt certificate that should be quite universally valid.

**Comment by AlexandrePTJ** [comment]
I will try then. It had some issues with https. Thanks you for your help.
