### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by ZeiP** [AlexandrePTJ/kemai#22]
When trying to launch the program in a Fedora Linux and Wayland / Sway environment, I only got the following shell output:

```
zeip@jameson ~ » ~/softat/Kemai.AppImage             
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

[1]    333853 abort (core dumped)  ~/softat/Kemai.AppImage
```

Would it be difficult to add native Wayland support for the application? I did get it to work by specifying the xcb platform:
```
QT_QPA_PLATFORM=xcb ~/softat/Kemai.AppImage
```
This, however, isn't optimal as it's then not a native Wayland application.

**Comment by AlexandrePTJ** [comment]
It may be possible to add env vars in AppImage. I will check.
