### ISSUE TITLE
"Started at" can not be modified 

### ISSUE THREAD

**Issue by shrippen** [AlexandrePTJ/kemai#26]
Hi there,

first let me say that I use your Kimai client nearly daily and am glad that you made it. I have a small request or question. At the bottom of the window you have an area with "Started at" and a dropdown menu for the time. Thing is - that dropdown menu is greyed out. Is there a way to use it? Sometimes I forget to start the timer timely and have to start my activitys a bit in the past. At the moment I start my acitivity with Kemai and then have to correct the start time in my Kimai instance. I would like to get rid of that extra step and correct the start time directly in Kemai.

**Comment by AlexandrePTJ** [comment]
Thanks you for the feedback.

Currently, there is no way to update it. However, it is a good idea to let user change it.
