### ISSUE TITLE
[Improvement] Allow Description Editing during Time Record

### ISSUE THREAD

**Issue by lukas681** [AlexandrePTJ/kemai#43]
Hi there,

A small feature request: As I use Kemai along my workday to track my working time and we also create a work report at the end of the month, I fill my tasks into the description field in parallel to my work I do.

Unfortunately, this is not reflected to be send back to the server (as far as I have seen it by now). 

One possibility would be to synchronize the description field again, once the current time record is being stopped. Alternatively, a synch button could be placed next to the description field to enable the same requirement.

**Comment by AlexandrePTJ** [comment]
Thanks you for the idea.

**Comment by lukas681** [comment]
Glad to hear!
