### ISSUE TITLE
[Improvement] Improve Loading of Customer / Projects / Activities

### ISSUE THREAD

**Issue by lukas681** [AlexandrePTJ/kemai#44]
Sorry, for spamming the issues section. Another Idea that came into my mind. :)

Fetching the list of all projects/activities everytime new is cumbersome as so has to wait a few seconds until everything is displayed correctly and fetched from the server. It would be great to have a refresh button that loads all the values only on demand / maybe schedule some planned pulls. But for quickly switching between projects this would be pretty helpful ...

**Comment by AlexandrePTJ** [comment]
No worries about 'spamming'. This is also the right way for suggestions.

This improvement was already in my mind :) Then I keep this entry for tracking it.
