### ISSUE TITLE
Cumulative time column

### ISSUE THREAD

**Issue by bernd-wechner** [AlexandrePTJ/kemai#45]
Small feature request to cover a standard use case currently.

The use case:

1. Export all times this week as CSV
2. Open in Excel
3. Divide all durations by 3600
4. Sum them

This is for time management. Anyone who has X hours per week, or fortnight or month to deliver to track cumulative progress, not least on the last day of the period. 

The problem of course is that work periods and commitment vary a lot.

A simple suggestion would be to make three new columns available:

1. Cumulative duration this week
2. Cumulative duration this fortnight (2 weeks)
3. Cumulative duration this month

Of course specific people might want more granularity by project, activity or tag.  I can't think of an easy way to accommodate that off hand and hope it's not an argument against at least a few nice cumulative duration 

There are more complicated ways I can imagine handling it of course but would not want to see this simple idea bogged down by complexity that could come later. One idea would of course be to have a custom cumulative column that can be created which includes a time bracket, project, activity and tag filter. User defined columns to add. Just a thought but as I said, would rather see a broad sweeping sum than none to see an end to the regular exports and spreadsheet sums I'm doing ;-)

**Comment by AlexandrePTJ** [comment]
Hi,

Sorry for the delayed response, but I think this suggestion is for Kimai project. Kemai is just a client to handle simple tasks.
