### ISSUE TITLE
Input Focus and Tabbing Order Suggestion

### ISSUE THREAD

**Issue by sdreilinger** [AlexandrePTJ/kemai#48]
### Input Focus and Tabbing Order Suggestion

Hello @AlexandrePTJ :

I am using Kemai compiled from the master branch, and appreciate your desktop client very much!

Please consider specifying the input focus and tab order in the Add Customer, Add Project, and Add Activity dialog boxes.

### Add Customer Dialog 

**Input focus** defaults to the second field: _Customer_. 
Suggested input focus: _Name_.

**Tab order** currently goes from:
`                Country->Timezone->Name->Currency->Budget->Time Budget`
Suggested tab order (based on dialog layout):
`                Name->Country->Timezone->Currency->Budget->Time Budget`

### Add Project Dialog
**Input focus** defaults to: _Budget_
Suggested input focus: _Name_

**Tab order** currently goes from:
`                Budget->Time Budget->Name`
Suggested tab order:
`                Name->Budget->Time Budget`

### Add Activity Dialog
**Input focus** defaults to: _Time Budget_
Suggested input focus: _Name_

**Tab order** currently goes from:
`                Time Budget->Name->Budget`
Suggested tab order:
`                Name->Budget->Time Budget`

### Documentation
This documentation may be relevant:
- https://doc.qt.io/qt-5/designer-tab-order.html
- https://doc.qt.io/qt-5/qwidget.html#setTabOrder
- https://doc.qt.io/qt-5/qwidget.html#setFocus-1

**Comment by AlexandrePTJ** [comment]
@sdreilinger Thank you for the suggestion and the PR.
