### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by Nasuada** [AlexandrePTJ/kemai#5]
Hi, 

I try to config that App under Mac OS, but without a result yet. 
Especially it would a Token and I have no Idea, where I got this.

As Host I fill in my URL to Kimai.
Sample: https://b*******l.de/timetrack/
Username: My Loginname
Token: ???

So I'm new on Kimai and I'm a bit confused... Where I get the correct details? 
Kimai is running on my Server as FTP installation. 

Thanks for help.

**Comment by AlexandrePTJ** [comment]
From Kimai, click on your profile icon (top right), then on "Edit"
There is an API tab, set a password. This this password you have to use as token for Kemai settings.

**Comment by Nasuada** [comment]
Thanks for your quick replay. 

Sadly still not work. I found the API Setting, let generate a Passwort with 1Password, fill that in the Settings, safe it and still no connection after hitting the test button. As result I got this Info:
Error on request [version]: Error transfering https://b**********.de/api/version - server replied: Not found.

So I try different URL's like https://b*******l.de/timetrack/ or https://b*******l.de/timetrack/private/, but it not solve the connection Problem. 
Also I checked my installation on the FTP server. So there is no folder named "/api/version/". The version.php is in /src/API/Model/Version.php, if this file is needed for the desktop app. Another api Folder I didn't found yet. If I fill that URL inside the HOST, it also will not work. It still try to point to https://b**********.de/api/version. 

In installed Kimai 2 - 1.9 stable on my shared hoster.

**Comment by AlexandrePTJ** [comment]
Does your instance is directly at something like https://kimai.my.com/ or in a subdir like https://my.com/kimai/ ?

**Comment by Nasuada** [comment]
Kamai is installed in a subdirectory and the full path to that is "https://b*******l.de/timetrack/". To reach the Website, I need to open https://b*******l.de/timetrack/private/ (as described in the manual for an FTP installation).

**Comment by AlexandrePTJ** [comment]
Thanks you for the details. Then it is a bug, I will fix soon.

**Comment by Nasuada** [comment]
Thank you. 

If you need any more details or need an access to my installation, feel free to send me a mail. 
You can use robinalbeck[at]gmail . com (sorry for that form of my Mail. I try to let it SPAM Free ;-) )

**Comment by AlexandrePTJ** [comment]
This is fixed and available in 0.2.0 version.

**Comment by Nasuada** [comment]
Thanks for fix that. It running from now.
