### ISSUE TITLE
SSL Handshake failed on macos version

### ISSUE THREAD

**Issue by shrippen** [AlexandrePTJ/kemai#54]
Hi,

I have recently tried to use your most excellent program on MacOS. Sadly it can not connect to my kimai instance. I've tried the same kimai instance with the recent kemai version on Windows, and the kimai offline tracker for ios and it works flawlessly. So it seems to be related to the specific macos build.

This is the error message: 
Error on request [version]: SSL handshake failed

Do you have an idea how I can fix this?

**Comment by AlexandrePTJ** [comment]
Hi @shrippen,

It may be related to missing cert file in archive. I will check and update.

**Comment by shrippen** [comment]
Thanks. I did also test the 0.7.0 and 0.6.0 versions which show the same behaviour.

**Comment by larsvonhier** [comment]
Same problem here with version 0.7.1
Fix is needed or at least a workaround - can cert file(s) be injected or ignored somehow?

**Comment by AlexandrePTJ** [comment]
Do you use self-signed certificates ?
I tried to connect to [https://demo-stable.kimai.org](https://demo-stable.kimai.org) and it worked (From OSX Monterey).

**Comment by shrippen** [comment]
Yes i do, via caddy and letsencrypt

Von: Alexandre Petitjean ***@***.***>
Gesendet: Mittwoch, 3. August 2022 21:34
An: AlexandrePTJ/kemai ***@***.***>
Cc: shrippen ***@***.***>; Mention ***@***.***>
Betreff: Re: [AlexandrePTJ/kemai] SSL Handshake failed on macos version (Issue #54)


Do you use self-signed certificates ?
I tried to connect to https://demo-stable.kimai.org<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdemo-stable.kimai.org%2F&data=05%7C01%7C%7C4eb8eb6bf47344a1152f08da75872671%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637951520576992713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xt3YodpYDNw8LO8rftoEZwnjGGRH9vaGyyzgsJZJmZI%3D&reserved=0> and it worked (From OSX Monterey).

-

**Comment by larsvonhier** [comment]
Certs might be self signed (we host the data base on a local Mac Pro in our intranet), Kimai via web interface works fine though.

**Comment by AlexandrePTJ** [comment]
It was a packaging problem. Fixed for the next release.

**Comment by AlexandrePTJ** [comment]
@shrippen @larsvonhier Here is a newly generated version for Mac OSX. Would you please test it and tell me if SSL is fine.
I tested from my side, it looks ok.
[Kemai macos-latest.zip](https://github.com/AlexandrePTJ/kemai/files/9414895/Kemai.macos-latest.zip)
