### ISSUE TITLE
Option to stop recording when the screen locks?

### ISSUE THREAD

**Issue by sdreilinger** [AlexandrePTJ/kemai#55]
Greetings @AlexandrePTJ:

This is an enhancement suggestion:

Would it be possible to have an option to **stop** the user's current Kemai recording when the **screen is locked**?

Would monitoring this Qt signal: **applicationStateChanged** make it possible?

https://doc.qt.io/qt-5/qguiapplication.html#applicationStateChanged
https://doc.qt.io/qt-5/qt.html#ApplicationState-enum

Thanks for very much for considering it!

**Comment by AlexandrePTJ** [comment]
Thank you @sdreilinger for this proposal.
I do like the idea !

**Comment by AlexandrePTJ** [comment]
Only Windows is available for now
