### ISSUE TITLE
Time not listet # Method not allowed

### ISSUE THREAD

**Issue by asaglam76** [AlexandrePTJ/kemai#56]
Hello Alexandre,
I'm trying to run the desktop client.
The access is successfull, but the counter is not working. I checked the log file and it seems, there is something wrong .. the cut of log below.

####
{"code":405,"message":"Method Not Allowed"}
[2022-09-10 10:38:35.957] [kemai] [debug] ===> [PATCH] http://fqdn/api/timesheets/0/stop
[2022-09-10 10:38:36.010] [kemai] [error] Client error: Error on request [timesheets]: Error transferring https://fqdn/api/timesheets/0/stop - server replied: Method Not Allowed
{"code":405,"message":"Method Not Allowed"}
[2022-09-10 10:38:40.919] [kemai] [debug] ===> [PATCH] http://fqdn/api/timesheets/0/stop
[2022-09-10 10:38:40.975] [kemai] [error] Client error: Error on request [timesheets]: Error transferring https://fqdn/api/timesheets/0/stop - server replied: Method Not Allowed
####
![grafik](https://user-images.githubusercontent.com/46278841/189478068-d17908a8-02f3-4bcd-8109-820eaa7aa846.png)
####
I'm not sure about one thing. Is the plugin "Task planning" mandatory for the desktop client. If yes, then I have to test ist with the plugin, if not .. what can be the cause.

**Comment by AlexandrePTJ** [comment]
Hi @asaglam76,

"Task planning" is not mandatory. Kemai just check if it is enabled in kimai instance, then add another panel if needed.

For your problem, you have to ensure that the user you are using with your connection has the permission "edit_activity".

**Comment by asaglam76** [comment]
Hi Alexandre ..
think we're misunderstanding. I think the "Task Planning" need to be installed .. regardless of whether it is used or not, which means that it is installed and active. Without this plug-in, Kemai does not seem to work. I have also tried it with the admin user, same result. It is unfortunately a bit unfortunate that you cannot get the plugins as test versions.

**Comment by AlexandrePTJ** [comment]
Which version of kimai do you connect to ?

**Comment by asaglam76** [comment]
1.24 (the newest version) .. it is actually in test. I tried a lot of things, bought task planning ... it is not working :(

**Comment by livelace** [comment]
it doesn't work for me either.
tried with kimai version 1.29.1 (self hosted and cloud).
tried to use master branch, but no luck.

what i see in logs on my host:

>[2022-12-18 23:34:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /api/timesheets/0/stop": Method Not Allowed (Allow: PATCH)" at /data/app/kimai/vendor/symfony/http-kernel/EventListener/RouterListener.php line 140 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /api/timesheets/0/stop\": Method Not Allowed (Allow: PATCH) at /data/app/kimai/vendor/symfony/http-kernel/EventListener/RouterListener.php:140, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /data/app/kimai/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:42)"} []

**Comment by AlexandrePTJ** [comment]
This API method is not used anymore. Should be fixed since version 0.8.0.
