### ISSUE TITLE
Dual Monitor failure

### ISSUE THREAD

**Issue by dg3fbl** [AlexandrePTJ/kemai#59]
The Version 0.7.1 did not work here with two monitors. 
I can move the main window to both screens, that works. But the pull-down boxes opens every time on the wrong monitor. I did not find a solution. Have to go back to 0.6 Version, this version works without issue.

Any hints?

**Comment by AlexandrePTJ** [comment]
Which OS please ? (I tried on W10, it worked)

**Comment by dg3fbl** [comment]
> Which OS please ? (I tried on W10, it worked)

I am on Windows 10 Pro, 21H2 (19044.1889)

There is something else, the program always 
[IMG_2907.webm](https://user-images.githubusercontent.com/58482370/190083360-d8ccedc3-9fbb-4201-a501-1e2d39b637c1.webm)
opens on the left monitor. Even if I move it to the right and then close it.

**Comment by AlexandrePTJ** [comment]
Pretty strange behaviour !
What is the little green icon on the title bar ?

**Comment by dg3fbl** [comment]
> What is the little green icon on the title bar ?
This is a hardcopy tool that i use since years: hardcopy.de/hardcopy/english/index.php

**Comment by AlexandrePTJ** [comment]
Ok. I will check that.

**Comment by dg3fbl** [comment]
Worked  for me not with Version 0.9.3 !
Thanks
