### ISSUE TITLE
Client does not calculate times based on user's timezone

### ISSUE THREAD

**Issue by oli-ver** [AlexandrePTJ/kemai#6]
I have configured Kemai for the timezone Europe/Berlin. My operating system (Debian 10 Buster) is set to the same time.

When starting the clock the UI shows 22:00:00 as starting point:

![grafik](https://user-images.githubusercontent.com/965863/81497968-5f653380-92c2-11ea-9e9f-bda882c04b82.png)

After stopping the clock the web interface start and end times do not match, so no time can be calculated:

![grafik](https://user-images.githubusercontent.com/965863/81497995-87549700-92c2-11ea-9456-936ad2df3da1.png)

This is the logfile of the UI client:

```
===> [GET]   "https://kimai.my-host.hld/api/version"
===> [GET]   "https://kimai.my-host.hld/api/timesheets/active"
===> [GET]   "https://kimai.my-host.hld/api/customers"
===> [GET]   "https://kimai.my-host.hld/api/projects?customer=1"
===> [GET]   "https://kimai.my-host.hld/api/activities?project=2"
===> [GET]   "https://kimai.my-host.hld/api/activities?project=1"
===> [GET]   "https://kimai.my-host.hld/api/timesheets/active"
===> [GET]   "https://kimai.my-host.hld/api/customers"
===> [GET]   "https://kimai.my-host.hld/api/projects?customer=1"
===> [GET]   "https://kimai.my-host.hld/api/activities?project=1"
===> [POST]  "https://kimai.my-host.hld/api/timesheets" "{\n    \"activity\": 1,\n    \"begin\": \"2020-05-10T13:26:05\",\n    \"description\": \"\",\n    \"project\": 1\n}\n"
```

**Comment by AlexandrePTJ** [comment]
Thanks you for the feedback. This is fixed in develop branch.
