### ISSUE TITLE
Not all required libraries are included: libOpenGL.so.0 is missing

### ISSUE THREAD

**Issue by noseshimself** [AlexandrePTJ/kemai#60]
```
user@kraftwerk:/mnt/chromeos/MyFiles/Downloads$ ./Kemai-0.7.1-x86_64.AppImage 
./Kemai-0.7.1-x86_64.AppImage: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory
```

AppImages should be as independent as possible. Imagine running on a plain terminal-only Linux where all you will be provided with is a Wayland server and an XWayland. No additional libraries.

**Comment by AlexandrePTJ** [comment]
This is expected, as explained here: https://github.com/linuxdeploy/linuxdeploy/issues/152
