### ISSUE TITLE
Can't create Customer, Project or Activity

### ISSUE THREAD

**Issue by khromov** [AlexandrePTJ/kemai#62]
Just connected version 0.7.1 of the app on Windows 11 to a Kimai server running 1.26.0. Trying to create a Customer, Project or Activity does not work. After filling in all data and clicking OK, no error is shown, but the items are not created. Creating through the web UI works.

**Comment by AlexandrePTJ** [comment]
I did not already migrate to win11.
Can you share here your logfile ? Should be in %appdata%/kemai/kemai

**Comment by AlexandrePTJ** [comment]
@khromov Is it still the case with recent version of kemai ?

**Comment by AlexandrePTJ** [comment]
No feedback and cannot reproduce
