### ISSUE TITLE
Counter stuck on 00:00:00

### ISSUE THREAD

**Issue by khromov** [AlexandrePTJ/kemai#64]
When starting a task, the counter is stuck at 00:00:00 without any error messages. The stop button also does not work. I verified that the instance connects correctly using Settings > Profiles > Test. This is on Kimai 1.26.0.

![2022-10-16 23_28_29-Kemai - Kimai client](https://user-images.githubusercontent.com/1207507/196059195-ed3a89eb-fa38-4e42-9722-b97d9948fb75.png)

**Comment by AlexandrePTJ** [comment]
This happens when using Task plugin from Kimai ?

**Comment by donaldsv** [comment]
I have the same issue and i'm not using the Task plugin. Version 1.30.1 of Kimai

**Comment by AlexandrePTJ** [comment]
API client side have been re-written and it should be fixed since version 0.8.0
