### ISSUE TITLE
Create a Homebrew formula

### ISSUE THREAD

**Issue by martin-braun** [AlexandrePTJ/kemai#67]
Experienced Mac users prefer to install software with [Homebrew](brew.sh). Please consider to [create and publish a Homebrew Formula](https://docs.brew.sh/Formula-Cookbook) for this wonderful client. Thank you.

cc @kevinpapst

**Comment by kevinpapst** [comment]
@martin-braun you could create the formula as well, if you see a need for it?

**Comment by AlexandrePTJ** [comment]
I have no idea on how homebrew works. However as it is widely used, I will take a look.

**Comment by AlexandrePTJ** [comment]
Should use https://github.com/Homebrew/homebrew-cask

**Comment by AlexandrePTJ** [comment]
Looks like Kemai does not fit for cask submission:
`GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)`

**Comment by martin-braun** [comment]
@AlexandrePTJ Had no idea about that limitation. You could still publish your own tap, but it's ok, don't bother with it until there is more interest.

**Comment by kevinpapst** [comment]
Let's keep this open. If the formula is already here, it is just a matter of time to reach that limit.
I shared the story at Mastodon https://phpc.social/@kimai/110728658150012028 and will do the same at Twitter later.

**Comment by AlexandrePTJ** [comment]
Thanks you for sharing !

I will submit :)

**Comment by kevinpapst** [comment]
Glad we did it so fast. Good luck with the submission 👍 keep us updated

**Comment by AlexandrePTJ** [comment]
PR have been submitted: https://github.com/Homebrew/homebrew-cask/pull/151207

**Comment by kevinpapst** [comment]
My Mac is still Intel based, so I can't really test...

Not sure if that article is still up-to-date: 
https://eclecticlight.co/2020/08/22/apple-silicon-macs-will-require-signed-code/

Maybe it helps.

**Comment by martin-braun** [comment]
@kevinpapst same. Wow that's really annoying to begin with. I think the reasoning is that people need to right click / open an application to run it, if it's unsigned. It also requires to toggle a setting to allow apps from unknown developers, so I understand their decision.
