### ISSUE TITLE
App Crashes directly after launch

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [AlexandrePTJ/kemai#70]
I just installed Kemai 0.8.0 for the first time but upon starting the main program window appears but nothing can be clicked and then it just closes again.

in the windows event viewer I can see an error with the following infos:
```
Faulting application name: Kemai.exe, version: 0.0.0.0, time stamp: 0x63af4d25
Faulting module name: Kemai.exe, version: 0.0.0.0, time stamp: 0x63af4d25
Exception code: 0xc0000005
Fault offset: 0x0000000000034830
Faulting process ID: 0x0x1D3C
Faulting application start time: 0x0x1D91EB5B6E023E8
Faulting application path: C:\Program Files\Kemai\Kemai.exe
Faulting module path: C:\Program Files\Kemai\Kemai.exe
Report ID: 51b0c6d1-63cf-4056-832b-6f2d47eb8aaa
Faulting package full name: 
Faulting package-relative application ID: 
```
I then installed 0.7.1 and this version does not crash.

Thanks for creating Kemai!

**Comment by AlexandrePTJ** [comment]
My bad, Kemai 0.8.0 should have been set as pre-release or beta version. This is current dev branch and I should not have been set as "latest" version.
