### ISSUE TITLE
Feature request:  Typing search

### ISSUE THREAD

**Issue by sollermun** [AlexandrePTJ/kemai#75]
Dropdown menus can be tedious because one needs to hunt and peck for the right project, customer, etc.

Currently, it is possible to type the first character of the menu item and narrow down the search. It would be better if the selection process narrows down to any item that includes the typed word.  For example, if the project name is Silver Lake, typing the word "lake" should take you to that item.

**Comment by shrippen** [comment]
The new implentation breaks the filtering of projects via customers. When I select a customer via dropdown the available projects are filtered accordingly. If I select a customer via typing and then use the dropdown menu for the projects it's not filtered at all.

Similarly when I first use the dropdown menu to select a customer it filters the projects for that customer. When I now change the customer by selecting another one via typing the projects are still filtered to the first customer that i selected via dropdown.
