### ISSUE TITLE
Dropdown fields for Customer, Project and Activity reset after every break

### ISSUE THREAD

**Issue by mrschaal** [AlexandrePTJ/kemai#77]
Since the latest update (0.8), the dropdown fields for customer, project and activity are always reset every time I stop the timer, so that I need to select the customer and/or project again every time I want to start time tracking again. This is quite annoying and disturbs my workflow if I'm just doing a pause or need to track another activity for the same project. 

Before the update, the dropdown fields stayed selected when pausing the time tracker, so that I've been able to continue immediately without any distraction.

**Comment by AlexandrePTJ** [comment]
Fixed with #44
