### ISSUE TITLE
SSL doesn't work on Windows

### ISSUE THREAD

**Issue by infeeeee** [AlexandrePTJ/kemai#8]
If I want to connect to a kimai server (even the demo instance) with https I get the following error: 

```
Error on request [version]: TLS initialization failed
```
![kép](https://user-images.githubusercontent.com/1271737/82031244-e25b0500-9699-11ea-9504-9f2e43ba70cb.png)

The demo is not reachable without https, but my instance is, so I could test, that this doesn't happen on plain http:

![kép](https://user-images.githubusercontent.com/1271737/82031817-ae341400-969a-11ea-913c-601c15ecb7d0.png)

![kép](https://user-images.githubusercontent.com/1271737/82031888-c6a42e80-969a-11ea-8295-da5d8730f31a.png)

I already had this issue with older kemai versions. Nor my server, nor the demo uses self-signed certificates.

Windows 10 1909.

**Comment by buoncri** [comment]
First of all, thanks for the software, than ...
Can this error be for not valid ssl certificate ?
![Annotazione 2020-05-21 110321](https://user-images.githubusercontent.com/3062441/82542888-06638e00-9b53-11ea-9852-6b5e1765d56a.png)

Is there a way to use ssl with self signed ?
Can be an option in configuration ?
