### ISSUE TITLE
Connection settings are not saved

### ISSUE THREAD

**Issue by fr-Fabix** [AlexandrePTJ/kemai#81]
Hello!

Thanks for this app!

I'm able to set up the connection but if I press the save button and go again to seetings, the complete setting ist deleted.

## before
![Bildschirm­foto 2023-04-03 um 15 40 58](https://user-images.githubusercontent.com/107420972/229527807-349913f7-e527-4408-aa31-6d194b4a3874.png)

## after
![Bildschirm­foto 2023-04-03 um 15 44 13](https://user-images.githubusercontent.com/107420972/229528143-753030e7-6a0e-4124-afd0-0d1b0db9a1ec.png)

## System:
mac mini

Mac OS 13.1

Thanks!

**Comment by de-es** [comment]
Can confirm that for the latest release (0.9.1) under Linux.

**Comment by fr-Fabix** [comment]
> Can confirm that for the latest release (0.9.1) under Linux.

thx for your quick reply!

**Comment by zu3st-de** [comment]
windows version also

**Comment by de-es** [comment]
Merci beaucoup! :heart: 

A minor observation: If you change the name of an existing profile, the name does not get updated in the profiles dropdown menu right aways. But it gets updated with a restart. Don't know if worth fixing.

**Comment by AlexandrePTJ** [comment]
@de-es Thanks for the report. It does not need a hotfix, but sure it must be fixed.
#82 created for this.
