### ISSUE TITLE
Sorting of customers

### ISSUE THREAD

**Issue by shrippen** [AlexandrePTJ/kemai#84]
Since I think 0.9 my list of customers is sorted differently in the dropdown menu. It used to be Aa -> Zz now it is A->Z a->z.
So
Company A
Company B
company a
company b

instead of

Company A
company a
Company B
company b

**Comment by AlexandrePTJ** [comment]
Sorry I didn't realize that behaviour

**Comment by shrippen** [comment]
Now all customers are sorted by Kimai ID :(
