### ISSUE TITLE
Kemai does not start

### ISSUE THREAD

**Issue by amanzone** [AlexandrePTJ/kemai#88]
Hi, I'm trying to update my Kemai.

OS: Ubuntu 23.04
Qt version: 6.5.0

I've tried both the Appimage and to build version 0.9.2 but I get similar results.

When I start the AppImage from the command line I get nothing, it seems not to be crashing but I'm left with a pending bash, no windows open and I can only close with Ctrl-C:

> $> ~/Tmp/Kemai-0.9.2-x86_64.AppImage 
> 
> 

I have also built with the following command:
`cmake . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/albi/Qt/6.5.0/gcc_64/`
(this is where Qt6 was installed by running the installation script: qt-unified-linux-x64-4.5.2-online.run)

Here is the build log:

> -- The CXX compiler identification is GNU 12.2.0
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
> -- Conan: checking conan executable
> -- Conan: Found program /home/albi/.venv/bin/conan
> -- Conan: Version found Conan version 1.59.0
> -- Conan executing: /home/albi/.venv/bin/conan install /home/albi/Tmp/kemai/kemai-0.9.2 --build missing --settings build_type=Release --settings compiler=gcc --settings compiler.version=12 --settings compiler.libcxx=libstdc++11 --settings compiler.cppstd=20
> Configuration:
> [settings]
> arch=x86_64
> arch_build=x86_64
> build_type=Release
> compiler=gcc
> compiler.cppstd=20
> compiler.libcxx=libstdc++11
> compiler.version=12
> os=Linux
> os_build=Linux
> [options]
> [build_requires]
> [env]
> 
> conanfile.py: Installing package
> Requirements
>     fmt/9.1.0 from 'conancenter' - Cache
>     magic_enum/0.8.2 from 'conancenter' - Cache
>     spdlog/1.11.0 from 'conancenter' - Cache
> Packages
>     fmt/9.1.0:d7ced63e92f33b9600eb9de2310cba21cf7d43de - Cache
>     magic_enum/0.8.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
>     spdlog/1.11.0:5c6c18cc5cb87f2d7be932997f9b8410e63bccfe - Cache
> 
> Installing (downloading, building) binaries...
> fmt/9.1.0: Already installed!
> magic_enum/0.8.2: Already installed!
> spdlog/1.11.0: Already installed!
> conanfile.py: Generator txt created conanbuildinfo.txt
> conanfile.py: Generator cmake_find_package created Findspdlog.cmake
> conanfile.py: Generator cmake_find_package created Findmagic_enum.cmake
> conanfile.py: Generator cmake_find_package created Findfmt.cmake
> conanfile.py: Aggregating env generators
> conanfile.py: Generated conaninfo.txt
> conanfile.py: Generated graphinfo
> -- Performing Test HAVE_STDATOMIC
> -- Performing Test HAVE_STDATOMIC - Success
> -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
> -- Using Qt 6.5.0
> -- Conan: Using autogenerated Findspdlog.cmake
> -- Found spdlog: 1.11.0 (found version "1.11.0") 
> -- Library spdlog found /home/albi/.conan/data/spdlog/1.11.0/_/_/package/5c6c18cc5cb87f2d7be932997f9b8410e63bccfe/lib/libspdlog.a
> -- Found: /home/albi/.conan/data/spdlog/1.11.0/_/_/package/5c6c18cc5cb87f2d7be932997f9b8410e63bccfe/lib/libspdlog.a
> -- Conan: Using autogenerated Findfmt.cmake
> -- Found fmt: 9.1.0 (found version "9.1.0") 
> -- Library fmt found /home/albi/.conan/data/fmt/9.1.0/_/_/package/d7ced63e92f33b9600eb9de2310cba21cf7d43de/lib/libfmt.a
> -- Found: /home/albi/.conan/data/fmt/9.1.0/_/_/package/d7ced63e92f33b9600eb9de2310cba21cf7d43de/lib/libfmt.a
> -- Library fmt found /home/albi/.conan/data/fmt/9.1.0/_/_/package/d7ced63e92f33b9600eb9de2310cba21cf7d43de/lib/libfmt.a
> -- Found: /home/albi/.conan/data/fmt/9.1.0/_/_/package/d7ced63e92f33b9600eb9de2310cba21cf7d43de/lib/libfmt.a
> -- Library spdlog found /home/albi/.conan/data/spdlog/1.11.0/_/_/package/5c6c18cc5cb87f2d7be932997f9b8410e63bccfe/lib/libspdlog.a
> -- Found: /home/albi/.conan/data/spdlog/1.11.0/_/_/package/5c6c18cc5cb87f2d7be932997f9b8410e63bccfe/lib/libspdlog.a
> -- Conan: Using autogenerated Findmagic_enum.cmake
> -- Found magic_enum: 0.8.2 (found version "0.8.2") 
> -- The C compiler identification is GNU 12.2.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/albi/Tmp/kemai/kemai-0.9.2/build
> 

I may have doubts regarding the correct configuration of Qt6, but it says: `-- Using Qt 6.5.0`

Also in this case I'm left with a pending bash, but with an additional message:

> $ ./build/src/Kemai
> qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
> 
> 

Also in this case no windows come up and I can only stop execution wit Ctrl-C

I would assume that Kemai is actually running but there's some issue with graphics, maybe something wrong with the Qt installation but I would not know how to track this down and fix it.

Any help is welcome!

Thanks in advance,
A.

**Comment by AlexandrePTJ** [comment]
Thanks for the report. I will have to raise an ubuntu VM before trying to reproduce, but you already gives all required informations.

**Comment by amanzone** [comment]
Many thanks!

Don't know if this helps, but in order to compile I had to force install version 1.59 of conan. It was failing usind up to date versions of conan (conan 2)

**Comment by AlexandrePTJ** [comment]
New 0.9.3 version should work fine. Please tell me.

**Comment by amanzone** [comment]
Hi, thanks for your update.

I've tried just now, but I'm at the office and here I have a windows PC running WSL. Unfortunately I have exactly the same behaviour as before, both running the AppImage and building on my own.

`myuser@mypc:~/Tmp/kemai-0.9.3$ cmake . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/qt6/
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build spdlog: 1.11.0
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Build type: Release
-- Found Git: /usr/bin/git (found version "2.37.2")
-- [range-v3]: C++ std=2a
-- Performing Test RANGES_HAS_CXXSTD
-- Performing Test RANGES_HAS_CXXSTD - Success
-- Performing Test RANGES_HAS_WALL
-- Performing Test RANGES_HAS_WALL - Success
-- Performing Test RANGES_HAS_WEXTRA
-- Performing Test RANGES_HAS_WEXTRA - Success
-- Performing Test RANGES_HAS_WERROR
-- Performing Test RANGES_HAS_WERROR - Success
-- Performing Test RANGES_HAS_FDIAGNOSTIC_SHOW_TEMPLATE_TREE
-- Performing Test RANGES_HAS_FDIAGNOSTIC_SHOW_TEMPLATE_TREE - Success
-- Performing Test RANGES_HAS_FTEMPLATE_BACKTRACE_LIMIT
-- Performing Test RANGES_HAS_FTEMPLATE_BACKTRACE_LIMIT - Success
-- Performing Test RANGES_HAS_FMACRO_BACKTRACE_LIMIT
-- Performing Test RANGES_HAS_FMACRO_BACKTRACE_LIMIT - Failed
-- Performing Test RANGES_HAS_OMIT_FRAME_POINTER
-- Performing Test RANGES_HAS_OMIT_FRAME_POINTER - Success
-- Performing Test RANGES_HAS_OFAST
-- Performing Test RANGES_HAS_OFAST - Success
-- Performing Test RANGES_HAS_STRICT_ALIASING
-- Performing Test RANGES_HAS_STRICT_ALIASING - Success
-- Performing Test RANGES_HAS_STRICT_VTABLE_POINTERS
-- Performing Test RANGES_HAS_STRICT_VTABLE_POINTERS - Failed
-- Performing Test RANGES_HAS_FAST_MATH
-- Performing Test RANGES_HAS_FAST_MATH - Success
-- Performing Test RANGES_HAS_VECTORIZE
-- Performing Test RANGES_HAS_VECTORIZE - Failed
-- Performing Test RANGES_HAS_SIZED_DEALLOCATION
-- Performing Test RANGES_HAS_SIZED_DEALLOCATION - Success
-- Performing Test RANGES_HAS_MARCH_NATIVE
-- Performing Test RANGES_HAS_MARCH_NATIVE - Success
-- Performing Test RANGES_HAS_MTUNE_NATIVE
-- Performing Test RANGES_HAS_MTUNE_NATIVE - Success
-- Performing Test RANGE_V3_ALIGNED_NEW_PROBE
-- Performing Test RANGE_V3_ALIGNED_NEW_PROBE - Success
-- Performing Test RANGE_V3_HAS_FCONCEPTS
-- Performing Test RANGE_V3_HAS_FCONCEPTS - Success
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
-- Using Qt 6.3.1
-- The C compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/myuser/Tmp/kemai-0.9.3/build
myuser@mypc:~/Tmp/kemai-0.9.3$ cmake --build build --config Release
[  1%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/spdlog.cpp.o
[  3%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o
[  5%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/color_sinks.cpp.o
[  7%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/file_sinks.cpp.o
[  9%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/async.cpp.o
[ 11%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/cfg.cpp.o
[ 13%] Building CXX object _deps/spdlog-build/CMakeFiles/spdlog.dir/src/bundled_fmtlib_format.cpp.o
[ 15%] Linking CXX static library libspdlog.a
[ 15%] Built target spdlog
[ 17%] Automatic MOC and UIC for target Kemai
[ 17%] Built target Kemai_autogen
[ 19%] Generating kemai_tr.qm
Updating '/home/myuser/Tmp/kemai-0.9.3/build/src/kemai_tr.qm'...
    Generated 63 translation(s) (63 finished and 0 unfinished)
[ 21%] Automatic RCC for resources/data.qrc
[ 23%] Automatic RCC for resources/icons.qrc
[ 25%] Generating kemai_cs.qm
Updating '/home/myuser/Tmp/kemai-0.9.3/build/src/kemai_cs.qm'...
    Generated 60 translation(s) (60 finished and 0 unfinished)
[ 26%] Generating kemai_it.qm
Updating '/home/myuser/Tmp/kemai-0.9.3/build/src/kemai_it.qm'...
    Generated 45 translation(s) (45 finished and 0 unfinished)
    Ignored 18 untranslated source text(s)
[ 28%] Generating kemai_nl.qm
Updating '/home/myuser/Tmp/kemai-0.9.3/build/src/kemai_nl.qm'...
    Generated 63 translation(s) (63 finished and 0 unfinished)
[ 30%] Generating kemai_nb_NO.qm
Updating '/home/myuser/Tmp/kemai-0.9.3/build/src/kemai_nb_NO.qm'...
    Generated 63 translation(s) (62 finished and 1 unfinished)
[ 32%] Generating kemai_fr.qm
Updating '/home/myuser/Tmp/kemai-0.9.3/build/src/kemai_fr.qm'...
    Generated 63 translation(s) (63 finished and 0 unfinished)
[ 34%] Generating kemai_de.qm
Updating '/home/myuser/Tmp/kemai-0.9.3/build/src/kemai_de.qm'...
    Generated 63 translation(s) (63 finished and 0 unfinished)
[ 36%] Generating kemai_el.qm
Updating '/home/myuser/Tmp/kemai-0.9.3/build/src/kemai_el.qm'...
    Generated 58 translation(s) (58 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)
[ 38%] Generating kemai_hr.qm
Updating '/home/myuser/Tmp/kemai-0.9.3/build/src/kemai_hr.qm'...
    Generated 63 translation(s) (63 finished and 0 unfinished)
[ 40%] Automatic RCC for l10n.qrc
[ 42%] Building CXX object src/CMakeFiles/Kemai.dir/Kemai_autogen/mocs_compilation.cpp.o
[ 44%] Building CXX object src/CMakeFiles/Kemai.dir/client/kimaiapi.cpp.o
[ 46%] Building CXX object src/CMakeFiles/Kemai.dir/client/kimaiCache.cpp.o
[ 48%] Building CXX object src/CMakeFiles/Kemai.dir/client/kimaiclient.cpp.o
[ 50%] Building CXX object src/CMakeFiles/Kemai.dir/client/kimaireply.cpp.o
[ 51%] Building CXX object src/CMakeFiles/Kemai.dir/client/parser.cpp.o
[ 53%] Building CXX object src/CMakeFiles/Kemai.dir/context/kemaisession.cpp.o
[ 55%] Building CXX object src/CMakeFiles/Kemai.dir/gui/activitydialog.cpp.o
[ 57%] Building CXX object src/CMakeFiles/Kemai.dir/gui/activitywidget.cpp.o
[ 59%] Building CXX object src/CMakeFiles/Kemai.dir/gui/autoCompleteComboBox.cpp.o
[ 61%] Building CXX object src/CMakeFiles/Kemai.dir/gui/customerdialog.cpp.o
[ 63%] Building CXX object src/CMakeFiles/Kemai.dir/gui/durationedit.cpp.o
[ 65%] Building CXX object src/CMakeFiles/Kemai.dir/gui/mainwindow.cpp.o
[ 67%] Building CXX object src/CMakeFiles/Kemai.dir/gui/projectdialog.cpp.o
[ 69%] Building CXX object src/CMakeFiles/Kemai.dir/gui/settingsdialog.cpp.o
[ 71%] Building CXX object src/CMakeFiles/Kemai.dir/gui/taskwidget.cpp.o
[ 73%] Building CXX object src/CMakeFiles/Kemai.dir/main.cpp.o
[ 75%] Building CXX object src/CMakeFiles/Kemai.dir/misc/datareader.cpp.o
[ 76%] Building CXX object src/CMakeFiles/Kemai.dir/models/kimaiDataListModel.cpp.o
[ 78%] Building CXX object src/CMakeFiles/Kemai.dir/models/kimaiDataSortFilterProxyModel.cpp.o
[ 80%] Building CXX object src/CMakeFiles/Kemai.dir/models/taskfilterproxymodel.cpp.o
[ 82%] Building CXX object src/CMakeFiles/Kemai.dir/models/tasklistmodel.cpp.o
[ 84%] Building CXX object src/CMakeFiles/Kemai.dir/monitor/desktopEventsMonitor.cpp.o
[ 86%] Building CXX object src/CMakeFiles/Kemai.dir/monitor/kimaiEventsMonitor.cpp.o
[ 88%] Building CXX object src/CMakeFiles/Kemai.dir/settings/settings.cpp.o
[ 90%] Building CXX object src/CMakeFiles/Kemai.dir/updater/kemaiupdater.cpp.o
[ 92%] Building CXX object src/CMakeFiles/Kemai.dir/monitor/linuxDesktopEventsMonitor.cpp.o
[ 94%] Building CXX object src/CMakeFiles/Kemai.dir/Kemai_autogen/3YJK5W5UP7/qrc_data.cpp.o
[ 96%] Building CXX object src/CMakeFiles/Kemai.dir/Kemai_autogen/3YJK5W5UP7/qrc_icons.cpp.o
[ 98%] Building CXX object src/CMakeFiles/Kemai.dir/Kemai_autogen/EJRQKI7XPS/qrc_l10n.cpp.o
[100%] Linking CXX executable Kemai
[100%] Built target Kemai
myuser@mypc:~/Tmp/kemai-0.9.3$ ./build/src/Kemai
`

Also in this case I'm left with a pending bash: no windows come up and I can only stop execution wit Ctrl-C

**Comment by amanzone** [comment]
I'll try again on my linux PC at home, but I do not expect any difference.
I'll let you know.

Thanks anyway!

**Comment by amanzone** [comment]
I did some some testing with AppImages...

Up to release 0.8.0 all Appimages seem to work.
Starting from release 0.9.0 no AppImages seem to be working, at least in my work setup: (WSL 2, running ubuntu 22.10)

**Comment by amanzone** [comment]
So, I just did an update to my WSL ubuntu installation. What it did was:

```
The following NEW packages will be installed:
  linux-headers-5.19.0-42 linux-headers-5.19.0-42-generic linux-image-5.19.0-42-generic
  linux-modules-5.19.0-42-generic linux-modules-extra-5.19.0-42-generic
The following packages will be upgraded:
  libfreetype6 libwebp7 libwebpdemux2 libwebpmux3 linux-firmware linux-generic linux-headers-generic
  linux-image-generic linux-libc-dev mdadm thermald
11 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
```

And then it removed old packages:

```
manzone@nb-manzone:~/Tmp$ sudo apt autoremove
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  linux-headers-5.19.0-31 linux-headers-5.19.0-31-generic linux-image-5.19.0-31-generic linux-modules-5.19.0-31-generic linux-modules-extra-5.19.0-31-generic
0 upgraded, 0 newly installed, 5 to remove and 0 not upgraded.
After this operation, 725 MB disk space will be freed.
Do you want to continue? [Y/n]
(Reading database ... 208433 files and directories currently installed.)
Removing linux-headers-5.19.0-31-generic (5.19.0-31.32) ...
Removing linux-headers-5.19.0-31 (5.19.0-31.32) ...
Removing linux-image-5.19.0-31-generic (5.19.0-31.32) ...
/etc/kernel/postrm.d/initramfs-tools:
update-initramfs: Deleting /boot/initrd.img-5.19.0-31-generic
Removing linux-modules-extra-5.19.0-31-generic (5.19.0-31.32) ...
Removing linux-modules-5.19.0-31-generic (5.19.0-31.32) ...
```

So, it was not really lagging behind very much in terms of updates, anyway now all AppImages work and likewise the 0.9.3 version I built on my own.

Honestly I do not believe the update really affected the result, but I did  not change anythig else either... so I really do not know what the issue was.
I'll try to replicate the success on my hone PC with ubuntu 23.04 and report back.

One thing only... is it possible that testing older relases did change anything in the setup? I do not see how...

**Comment by amanzone** [comment]
I tested with my linux PC and again version 0.9.3 started working ONLY AFTER I tested version 0.7.1, so I wonder if it may only be related to some weird stuff in the way the config files have evolved from the initial 0.4.0 release I was using?

In any case I believe it may be possible to close this issue now.

Thanks for your help!

**Comment by AlexandrePTJ** [comment]
@amanzone Thank you for the time spend on this analysis !
Setting file had changed from ini to json format. It may be the source of this problem.
