### ISSUE TITLE
Not able to use the Kemai mac client

### ISSUE THREAD

**Issue by maverickvarun** [AlexandrePTJ/kemai#9]
Hi 

We recently started using Kimai and found your app for Mac. I tried setting up but getting this error. 

Error on request [version]: Error transferring http://ts.developmentlogics.com/public/api/version - server replied: Not Acceptable 

How can we fix this?

thanks
Varun

**Comment by AlexandrePTJ** [comment]
Hi,

Did you create your api password from your profile page ?

**Comment by beitincapital** [comment]
Hey there,

I'm having a similar issue. I'm trying to use the Windows version of Kemai and I'm having trouble getting the program to connect to Kimai. I've created my api password from my profile page and used it as the token in Kemai with no luck. When I click on Help -> Open Kimai Instance, the program does open in a new browser window so I can tell that it is at least trying to connect but not sure why it returns as invalid reply. Any idea?

Thank you,

**Comment by AlexandrePTJ** [comment]
Version 0.3.0 have been released and should fix this issue. Please tell me if it is ok.
