### ISSUE TITLE
Focus Issues / Features for new contributors

### ISSUE THREAD

**Issue by muxelplexer** [AlexandrePTJ/kemai#91]
Hello, since i've been using the application extensively at my work place i plan to contribute to it :)
I took a look at the open issues but i'm cautious about starting work on one of them before checking no-one else is working on it yet.

What issue would be open to take or what else would be nice to do?

**Comment by AlexandrePTJ** [comment]
Hi @muxelplexer,

Thanks you for your proposal. I am very happy to hear about your will to contribute.
It makes me thinks that I need to write a CONTRIBUTE file to explains the best to start.

Issues with "good first issue" label are available. I you need more details, don't hesitate to talk about it :)

So, Welcome !

**Comment by muxelplexer** [comment]
Thank you very much for the quick response and the warm welcome :)

I'll start working on #57 and continue discussion over there if any questions arise!
